apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cwkueq81r-nodejs 
  janus-idp.io/tekton: cwkueq81r-nodejs
  backstage.io/kubernetes-id: cwkueq81r-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cwkueq81r-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  